### ISSUE TITLE
De code werkt niet als ik hem flash op mijn telefoon.

### ISSUE THREAD

**Issue by SimplyPancake** [Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-hidde-isabel#13]
Wanneer ik de code upload naar mijn eiFoon dan werkt mijn hele telefoon niet meer :(

Ik wil mijn geld 👎 😢 😭 🗡 ⚽️ 🍭 

> mai dok
[google.nl](https://www.youtube.com/watch?v=LnzYG0ZkrXg) @Pizzaaboi @isabelnieuwenhuis

**Comment by dadspaghetti** [comment]
yes hij werkt niet op mijn endrid plz send hulp

**Comment by SimplyPancake** [comment]
> yes hij werkt niet op mijn endrid plz send hulp

Hulp has bin sond
